// const IslamabadData = [
//   {
//     id: 'l1',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/296399887.webp?k=bfa80a1d4a62005eb7d78b1603acc7cb6f1a159b5cb65a9764bf3fe377ac994b&o=&s=1',
//     hotelName: 'Serenity Corner',
//     hotelAddress: 'Islamabad',
//     ' property': 'Travel Sustainable property',
//     appartmentType: 'Apartment with Mountain View',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 118m²',
//     // ""roomName"": 'Deluxe Double Room',
//     roomType: '5 beds (1 twin, 1 bunk bed, 1 sofa bed, 2 queens)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 5 rooms left at this price on our site',
//     roomPrice: 'PKR 16,500',
//     taxes: '+PKR 2,805 taxes and charges',
//   },
//   {
//     id: 'l2',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/138311481.webp?k=f100edae4570609f2e5b6c14fd6bc214d046ae871ef2ce654583001a4a6edfd5&o=&s=1',
//     hotelName: 'Centaurus Hotel Apartments',
//     hotelAddress: 'Blue Area, Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'One-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 1 living room • 1 bathroom • 1,057m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '1 full bed',
//     facilities: 'Breakfast included',
//     ' cancellation': 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 4 rooms left at this price on our site',
//     roomPrice: 'PKR 16,500',
//     taxes: '+PKR 2,805 taxes and charges',
//   },
//   {
//     id: 'l3',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/337837393.webp?k=69e540711f94f35a55ee89fa96cfb9b8d7c404d9a99aeccc03455ed6912296b1&o=&s=1',
//     hotelName:
//       'Three Bed Attached Bath Netflix Wifi Smart TV Parking WFH DeskOpens',
//     hotelAddress: 'Islamabad',
//     ' property': 'Travel Sustainable property',
//     appartmentType: 'Three-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 3 bedrooms • 1 living room • 3 bathrooms • 157m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '4 beds (1 sofa bed, 3 queens)',
//     facilities: 'Breakfast included',
//     // "cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 5 rooms left at this price on our site',
//     roomPrice: 'PKR 5,625',
//     taxes: '+PKR 956 taxes and charges',
//   },
//   {
//     id: 'l4',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/321319416.webp?k=045a7fe70096ff7b0b17f15d4d4a568b2b2455277d3ea8a7b07b084dfc422d71&o=&s=1',
//     hotelName: 'Freddy’s Luxury Apartments',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Apartment with Terrace',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 2 living rooms • 1 bathroom • 43m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '1 king bed',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 8,500',
//     taxes: '+PKR 1,445 taxes and charges',
//   },
//   {
//     id: 'l5',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/340154782.webp?k=0613130f3ec152df308a0e523538ad079a78ca0e494e3e5d0a6fecca7a33f976&o=&s=1',
//     hotelName: 'Roshan Heights',
//     hotelAddress: 'Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Two-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 780m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (2 kings, 1 sofa bed)',
//     facilities: 'Breakfast included',
//     ' cancellation': 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 7,200',
//     taxes: '+PKR 1,224 taxes and charges',
//   },
//   {
//     id: 'l6',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/346300345.webp?k=36b2c524ec403e18314f8e30cf06921bf422feda9d26d1e7e5e670db54dbb6af&o=&s=1',
//     hotelName: 'Spacious 2Bed Room Apartment',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Apartment - Ground Floor',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 2 living rooms • 2 bathrooms • 83m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '2 queen beds',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     // "leftRooms": 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 6,750',
//     taxes: '+PKR 1,148 taxes and charges',
//   },
//   {
//     id: 'l7',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/311550115.webp?k=effe7b1beea3cb6cf91dd0514c84aa2b84b4f6f9ab6c623f0b852d0c54846a9c&o=&s=1',
//     hotelName: 'Stunning Hill View Apartment/ 2BR/ Central City',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Apartment with Mountain View',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 102m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (1 king, 1 sofa bed, 1 queen)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     // "leftRooms": 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 7,800',
//     taxes: '+PKR 1,326 taxes and charges',
//   },
//   {
//     id: 'l8',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/349699667.webp?k=caf8962d76d994d0366915f294b0ea9b4d7dbc21d25b0a411dd8139099ce5c03&o=&s=1',
//     hotelName: 'Lovely 2 bed residential apartment in Islamabad',
//     hotelAddress: 'Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Two-Bedroom Apartment',
//     entireAppartment: 'Entire apartment • 1 living room • 2 bathrooms',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '1 sofa bed',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     // "leftRooms": 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 12,960',
//     taxes: '+PKR 2,203 taxes and charges',
//   },
//   {
//     id: 'l9',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/323279584.webp?k=74adfff6f76a6be510fad35c746ca3df7e3e1046040870a91fe088b691abfa48&o=&s=1',
//     hotelName: 'Upscale peaceful Penthouse 2king/BR isb view E11',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Penthouse Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 2 living rooms • 2 bathrooms • 139m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '4 beds (2 sofa beds, 2 queens)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     // "leftRooms": 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 11,999',
//     ' taxes': 'Includes taxes and fees',
//   },
//   {
//     id: 'l-10',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/310585994.webp?k=55b4ca3592f75c5eb91fb825b8d316ff9da994306c865782544ddffee761d209&o=&s=1',
//     hotelName:
//       'Luxury Executive 2Bedroom apartment Convenient and Nice Location',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 2 living rooms • 2 bathrooms • 186m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '4 11 beds (2 kings, 9 sofa beds)',
//     facilities: 'Breakfast included',
//     //" cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 12,600',
//     taxes: '+PKR 2,142 taxes and charges',
//   },
//   {
//     id: 'l-11',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/321029599.webp?k=3d1e92488408946b386841d8d39f296f14aec754b7ef22927d87f011c0b2089f&o=&s=1',
//     hotelName: 'Atrium high Suite 2bed family apartment near Giga Mall',
//     hotelAddress: 'Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Apartment with Mountain View',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 130m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '2 king beds',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 11,448',
//     taxes: '+PKR 1,946 taxes and charges',
//   },
//   {
//     id: 'l-12',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/330546473.webp?k=b7037b57c2ac057f67e106595ae751e3407e3146558d50392cfa681681f5698a&o=&s=1',
//     hotelName: 'Padspromo Lodge',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Apartment with Shower',
//     entireAppartment:
//       'Entire apartment • 3 bedrooms • 1 living room • 6 bathrooms • 2,302m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '7 beds (2 twins, 2 kings, 2 sofa beds, 1 queen)',
//     facilities: 'Breakfast included',
//     // "cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 11,448',
//     taxes: '+PKR 1,946 taxes and charges',
//   },
//   {
//     id: 'l-13',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/333446601.webp?k=a2cb7883e571f0e482484cdf7afaa8b3131a9ff9787c7544d9ee8a16c8b4f5af&o=&s=1',
//     hotelName: 'Lux Stays One Constitution Ave',
//     hotelAddress: 'Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'One-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 1 living room • 1 bathroom • 91m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '1 king bed',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 24,000',
//     taxes: '+PKR 4,080 taxes and charges',
//   },
//   {
//     id: 'l-14',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/341487967.webp?k=14e6c9edd4aae46136c9626d1e84d4c0947fccf2e31b1add499d09d8ec6a9e58&o=&s=1',
//     hotelName: 'BEST AFFORDABLE 3 BEDROOM LISTING WITH AMENITIES!!',
//     hotelAddress: 'Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Apartment - Ground Floor',
//     entireAppartment:
//       'Entire apartment • 3 bedrooms • 1 living room • 3 bathrooms',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 queen beds',
//     facilities: 'Breakfast included',
//     // "cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 12,150',
//     taxes: '+PKR 2,066 taxes and charges',
//   },
//   {
//     id: 'l-15',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/336510096.webp?k=f08bf9d3a525aca2d1f24aee6ca11d0366b914a39e9fcf6ac907ce530ee67608&o=&s=1',
//     hotelName: 'F-10 Spacious centrally located 2 Bed Apartment',
//     hotelAddress: 'Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Apartment with Balcony',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 139m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (1 sofa bed, 2 queens)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 9,950',
//     taxes: '+PKR 1,692 taxes and charges',
//   },
//   {
//     id: 'l-16',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/343364628.webp?k=b5c5fb506dc6d9bd03bd08ad1f0647cc9fd0bebe10aefdbc6a88a4dd72e7f95d&o=&s=1',
//     hotelName: 'Ikea Serviced Apartments',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Two-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (1 sofa bed, 2 queens)',
//     facilities: 'Breakfast included',
//     // "cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 5,850',
//     taxes: '+PKR 995 taxes and charges',
//   },
//   {
//     id: 'l-17',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/334124096.webp?k=a91bfb1e7a1e96c8b24ef31c052074672eb374e0acb467f9fa9b340426db794c&o=&s=1',
//     hotelName: 'Mini Condo-1BHK-Prime Location',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'One-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 1 living room • 1 bathroom • 60m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '2 beds (1 king, 1 sofa bed)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 5,500',
//     taxes: '+PKR 935 taxes and charges',
//   },
//   {
//     id: 'l-18',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/279093236.webp?k=c5736f20dd2236401ee1e71de45b430ae2a0be96cc38235efe9d9e6b7807a8de&o=&s=1',
//     hotelName:
//       'New & elegant Flat for Families, tourists, 4k Netflix, wifi, E11 Markaz',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     //" property": 'Travel Sustainable property',
//     appartmentType: 'Apartment',
//     entireAppartment: 'Entire apartment • 1 living room • 1 bathroom • 1,000m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '2 sofa beds',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 6,600',
//     taxes: '+PKR 1,122 taxes and charges',
//   },
//   {
//     id: 'l-19',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/343708953.webp?k=5de9a839817d32b04078f358a9b4c747c6679a5543288a1b83266fb0f6330b8c&o=&s=1',
//     hotelName: 'E-11, 2-BEDROOMS LUXURY APARTMENT',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Two-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 2 living rooms • 2 bathrooms • 195m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '16 beds (1 king, 14 sofa beds, 1 queen)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 13,950',
//     taxes: '+PKR 2,372 taxes and charges',
//   },
//   {
//     id: 'l-20',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/306369988.webp?k=f5bc5a993a796503bf2e2eecdabedc041e9c854c5c0537f450077cff8cc7f13e&o=&s=1',
//     hotelName: 'Serenity Corner',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Apartment - Ground Floor',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 1 living room • 1 bathroom • 84m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (2 sofa beds, 1 queen)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 7,500',
//     taxes: '+PKR 1,275 taxes and charges',
//   },
//   {
//     id: 'l-21',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/312664662.webp?k=6bfd9e77636d215822a69b228aab4d89905ec01ec44251a5d92a664d2ab7eb4a&o=&s=1',
//     hotelName: 'CityView-2BR-Central City',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     // "property": 'Travel Sustainable property',
//     appartmentType: 'Superior Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 84m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (1 king, 1 sofa bed, 1 futon)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 7,600',
//     ' taxes': '+PKR 1,292 taxes and charges',
//   },
//   {
//     id: 'l-22',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/328783892.webp?k=0458f29244cbd8caa20aaa6717e30e9df309257efe34398eb849d8a90ddc6ea7&o=&s=1',
//     hotelName: '2 Bedroom Appartment Near Airport & Moterway',
//     hotelAddress: 'Islamabad',
//     //"property": 'Travel Sustainable property',
//     appartmentType: 'Two-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 2 bedrooms • 1 living room • 2 bathrooms • 121m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '5 beds (1 sofa bed, 2 queens, 2 futons)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 20,000',
//     taxes: '+PKR 3,400 taxes and charges',
//   },
//   {
//     id: 'l-23',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/343712517.webp?k=12915d705cfe0b6ea0fe2c752c9711b036cab7770d18299908977c97f8f27aa1&o=&s=1',
//     hotelName: 'E-11 DAILY BASIS 3-BEDROOMS APARTMENT',
//     hotelAddress: 'E-11 Sector, Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Three-Bedroom Apartment',
//     entireAppartment:
//       'Entire apartment • 3 bedrooms • 3 living rooms • 3 bathrooms • 177m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '5 beds (3 kings, 2 sofa beds)',
//     facilities: 'Breakfast included',
//     cancellation: 'FREE cancellation • No prepayment needed',
//     cancellationTime:
//       'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 14,580s',
//     ' taxes': '+PKR 2,479 taxes and charges',
//   },
//   {
//     id: 'l-24',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/204500311.webp?k=7a79e6dca96ac8c5edb319e5f2555591b5730c7eb43660e1196432cd27be7f1a&o=&s=1',
//     hotelName: 'Luxurious Flat located in mid of Isb & isb airport',
//     hotelAddress: 'Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Apartment with Terrace',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 1 living room • 1 bathroom • 84m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '3 beds (2 sofa beds, 1 queen)',
//     facilities: 'Breakfast included',
//     // "cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 6,970',
//     taxes: '+PKR 1,066 taxes and charges',
//   },
//   {
//     id: 'l-25',
//     hotelImg:
//       'https://t-cf.bstatic.com/xdata/images/hotel/square200/324094943.webp?k=a88e0db00f414927f46e956c242e2f38f1b87034546f42613e274553a553de56&o=&s=1',
//     hotelName: 'Private Studio Apartment',
//     hotelAddress: 'Islamabad',
//     property: 'Travel Sustainable property',
//     appartmentType: 'Studio Apartment',
//     entireAppartment:
//       'Entire apartment • 1 bedroom • 1 living room • 1 bathroom • 74m²',
//     // "roomName": 'Deluxe Double Room',
//     roomType: '1 queen bed',
//     facilities: 'Breakfast included',
//     // "cancellation": 'FREE cancellation • No prepayment needed',
//     // "cancellationTime":
//     //   'You can cancel later, so lock in this great price today!',
//     stay: '1 night, 2 adults',
//     leftRooms: 'Only 1 room left at this price on our site',
//     roomPrice: 'PKR 7,000',
//     taxes: '+PKR 1,190 taxes and charges',
//   },
// ]

// export default IslamabadData
